export default [
  {
    id: 1,
    name: 'Leanne Graham',
    profileImage: 'icon/face',
    email: 'sincere@april.biz',
    phone: '123456789',
  },
  {
    id: 2,
    name: 'Ervin Howell',
    profileImage: 'icon/face',
    email: 'Shanna@melissa.tv',
    phone: '123456789',
      },
  {
    id: 3,
    name: 'Clementine Bauch',
    profileImage: 'icon/face',
    email: 'Nathan@yesenia.net',
    phone: '123456789',
  },
  {
    id: 4,
    name: 'Patricia Lebsack',
    profileImage: 'icon/face',
    email: 'Julianne.OConner@kory.org',
    phone: '123456789',
  },
  {
    id: 5,
    name: 'Chelsey Dietrich',
    profileImage: 'icon/face',
    email: 'Lucio_Hettinger@annie.ca',
    phone: '123456789',
  },
  {
    id: 6,
    name: 'Mrs. Dennis Schulist',
    profileImage: 'icon/face',
    email: 'Karley_Dach@jasper.info',
    phone: '123456789',
  },
  {
    id: 7,
    name: 'Kurtis Wessnat',
    profileImage: 'icon/face',
    email: 'Telly.Hoeger@billy.biz',
    phone: '123456789',
  },
  {
    id: 8,
    name: 'Nicholas Runolfsdottir V',
    profileImage: 'icon/face',
    email: 'Sherwood@rosamond.me',
    phone: '123456789',
  },
  {
    id: 9,
    name: 'Glenna Reichert',
    profileImage: 'icon/face',
    email: 'Chaim_McDermott@dana.io',
    phone: '123456789',
  },
]